name: Build

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 45

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: gradle-${{ hashFiles('checksum.txt') }}

      #  - name: Setup Gradle
      #    uses: gradle/gradle-build-action@v2

      - name: copy google-service
        env:
          GOOGLE_SERVICE: ${{ secrets.GOOGLE_SERVICE_JSON }}
        run: echo $GOOGLE_SERVICE | base64 --decode --ignore-garbage > ./app/google-services.json

      - name: Build project and UnitTest
        run: ./gradlew assembleDebug compileDebugUnitTestKotlin

      - name: Check spotless
        run: ./gradlew spotlessCheck --no-configuration-cache

      - name: Unit tests
        run: ./gradlew testDebugUnitTest

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Compile AndroidTests
        run: ./gradlew compileDebugAndroidTestKotlin

      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          arch: x86_64
          disable-animations: true
          disk-size: 2000M
          heap-size: 600M
          script: ./gradlew connectedDebugAndroidTest
